name: Scala Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Setup Eclipse Temurin - JDK 21
        uses: actions/setup-java@v3.13.0
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Tests
        run: sbt test
